language: node_js
deploy:
  provider: npm
  email: wcastan@gmail.com
  api_key:
    secure: DGaiaTSq+UGlUK3wmYwl48MKpjXrrCX1lowOeOflOakrqqnpCjZk8q5Y/6sPUsmtdsJd9VrcdvqZKN34f62E1ILosyHnBOtvYGxHhWe5FLU3z3fSSD52J4BjG6P1SDt80pxT7+K6Qj+sTdfQpRw4B7fOdAA+KlGC4Wgyb6+KIexkLzi81Q8QHFCQubarOMhrUwGgCwVk11hxKIHYRHSMo3ssU7dgyIoiEH/1GwuN8si4EEoegpHcU1BKmNp7PB/ZjpPwyN37DANrqvnu1VtX+tSJQOhov5AJqRHDbswHSHc/FIw/HDAan5jfUdahY+VFI7RS7+j/D61iDQ1kD+fWdBeUu2pIXQvn0Vo4nm3jkjLfwiBkmFCAhKLbPZ8V1Vq1gi6fM7Wg5SOj0Y7dBsb7/HertSFoPEOl4P1i+pd2J48Z4J8VsknBELSFvqAq8qNlaKpJWAb9cCEMwBsXtc5JeLU4Ej3ubQKEG2oMxgPuFQTkwSXhz9QtWcuEPH99trN6OiC6lEY75TNi37yDNmKmHBBlhk26Ywqasrgxv2im9ECsivyPffiS12DHyZR31lXF1PCC9ThJFPjAbevBjM6/sSXpoFq3w25BdCsBoRF6Q8ypx+5ecl/aZZIBe8SsQbPzdAdcpQuXD9jYZ4pngn3KnQ4L+ZHDWwSwLvENS15m1JU=
  on:
    tags: true
    repo: Kilix/storybook-addon-props-fela
api_key: 15a8e926-ad07-4863-93e3-868dd41fb55f
email: wcastand@gmail.com
provider: npm
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '7'
before_script:
- npm prune
script:
- npm run test
- npm run build
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
